module.exports = {
  PRODUCT_COLLECTION: "product",
  CATEGORY_COLLECTIONS: "category",
  BRAND_COLLECCTION:"brand",
  USERS_COLLECTION: "users",
  CART_COLLECTIONS:"cart",
  WISHLIST_COLLECTIONS:"wishlist",
  ORDER_COLLECTIONS:"order",
  ADDRESS_COLLECTIONS:"address",
  COUPONS_COLLECTIONS:"coupons",
  BANNER_COLLECTIONS:"banner",
  WALLET_COLLECTION:"wallet"
};
